In [1]:
import pandas as pd
import numpy as np
import pyreadr

In [2]:
def getData(data):
  return pyreadr.read_r(data)[None]

In [45]:
batch_df = getData("Batch.rds")
genetic_df = getData("Genetic.rds")
ocd_df = getData("OCD.rds")
que_df = getData("QUE.rds")
dmri_df  = getData("dMRI.rds")
smri_df  = getData("sMRI.rds")

In [33]:
batch_df.head()
batch_df['OCD']=batch_df['OCD'].fillna(1)
batch_df.head()

SampleID  OCD  Experimental  Test  Valid  Train_1  Train_2  \
0  NDAR_INV003RTV85  0.0           0.0   0.0    0.0      0.0      0.0   
1  NDAR_INV007W6H7B  0.0           0.0   0.0    0.0      0.0      0.0   
2  NDAR_INV00BD7VDC  1.0           1.0   0.0    0.0      0.0      0.0   
3  NDAR_INV00J52GPG  0.0           0.0   0.0    0.0      0.0      0.0   
4  NDAR_INV00LJVZK2  0.0           0.0   0.0    0.0      0.0      0.0   

   Train_3  Train_4  Train_5  ...  Train_69  Train_70  Train_71  Train_72  \
0      0.0      0.0      0.0  ...       1.0       0.0       0.0       0.0   
1      0.0      0.0      0.0  ...       0.0       0.0       0.0       0.0   
2      0.0      0.0      0.0  ...       0.0       0.0       0.0       0.0   
3      0.0      0.0      0.0  ...       0.0       0.0       0.0       1.0   
4      0.0      0.0      0.0  ...       0.0       0.0       0.0       0.0   

   Train_73  Train_74  Train_75  Train_76  ALL  TRAIN  
0       0.0       0.0       0.0       0.0  1.0    1.0  
1       0.0       0.0       1.0       0.0  1.0    1.0  
2       0.0       0.0       0.0       0.0  1.0    0.0  
3       0.0       0.0       0.0       0.0  1.0    1.0  
4       0.0       0.0       0.0       0.0  1.0    1.0  

[5 rows x 83 columns]

In [34]:
genetic_df.head()

SampleID  rs1806446  rs56242574  rs10904526  rs9423448  rs9423449  \
0  NDAR_INVTM382X5A     0.4985         0.5         0.5        0.5        0.5   
1  NDAR_INVYBXMBLAD     0.0000         0.0         0.0        0.0        0.0   
2  NDAR_INV0J6LY05U     0.4990         0.5         1.0        1.0        1.0   
3  NDAR_INV7PXH7ZBR     0.0000         0.0         0.5        0.5        0.5   
4  NDAR_INVZEB043HN     0.4740         0.5         0.0        0.0        0.0   

   rs9423659  rs11253241  rs72781967  rs7911497  ...  rs73665343  rs73665344  \
0      0.499       0.498       0.499      0.499  ...         0.0         0.0   
1      0.000       0.000       0.000      0.000  ...         0.5         0.5   
2      1.000       1.000       1.000      1.000  ...         0.5         0.5   
3      0.500       0.500       0.500      0.500  ...         0.5         0.5   
4      0.000       0.000       0.000      0.000  ...         0.5         0.5   

   rs73665345  rs73665346  rs73665347  rs59356096  rs60775187  rs73667907  \
0         0.0      0.0000      0.0000         0.0         0.0      0.0000   
1         0.5      0.5000      0.5000         0.5         0.5      0.5000   
2         0.5      0.5000      0.5000         0.5         0.5      0.4995   
3         0.5      0.4955      0.4955         0.5         0.5      0.4985   
4         0.5      0.5000      0.5000         0.5         0.5      0.5000   

   rs72762564  rs111926263  
0         1.0       0.9995  
1         0.0       0.0000  
2         0.5       0.5005  
3         0.0       0.4815  
4         0.0       0.0030  

[5 rows x 5655 columns]

In [35]:
ocd_df.head()
ocd_df['OCD']=ocd_df['OCD'].fillna(1)
ocd_df.head()

SampleID  OCD
0  NDAR_INV003RTV85  0.0
1  NDAR_INV007W6H7B  0.0
2  NDAR_INV00BD7VDC  1.0
3  NDAR_INV00J52GPG  0.0
4  NDAR_INV00LJVZK2  0.0

In [36]:
que_df.head()

SampleID  VAR_abcl_scr_sub_use_tobacco_r  \
0  NDAR_INV88RD5H70                        0.000000   
1  NDAR_INV8E597FU6                        0.000000   
2  NDAR_INV1H7NZZZ9                        0.005469   
3  NDAR_INVM6LR22KX                        0.033333   
4  NDAR_INVB2X30GHC                        0.000000   

   VAR_abcl_scr_sub_use_alcohol_r  VAR_abcl_scr_sub_use_drugs_r  \
0                        0.016484                      0.549451   
1                        0.021978                      0.000000   
2                        0.018810                      0.025732   
3                        0.000000                      0.000000   
4                        0.000000                      0.000000   

   VAR_abcl_scr_adapt_friends_r  VAR_abcl_scr_prob_anxious_r  \
0                      0.416667                     0.240000   
1                      0.583333                     0.040000   
2                      0.585739                     0.121704   
3                      0.583333                     0.000000   
4                      0.583333                     0.000000   

   VAR_abcl_scr_prob_withdrawn_r  VAR_abcl_scr_prob_somatic_r  \
0                       0.500000                     0.125000   
1                       0.111111                     0.062500   
2                       0.108259                     0.083987   
3                       0.000000                     0.000000   
4                       0.000000                     0.000000   

   VAR_abcl_scr_prob_thought_r  VAR_abcl_scr_prob_attention_r  ...  \
0                     0.090909                       0.545455  ...   
1                     0.000000                       0.121212  ...   
2                     0.028203                       0.144583  ...   
3                     0.000000                       0.030303  ...   
4                     0.000000                       0.000000  ...   

   VAR_demog_rent  VAR_demog_evict  VAR_demog_offserv  VAR_demog_doc  \
0             0.0              0.0                0.0            0.5   
1             0.0              0.0                0.0            0.0   
2             0.0              0.0                0.0            0.0   
3             0.0              0.0                0.0            0.0   
4             0.0              0.0                0.0            0.0   

   VAR_demog_dent  VAR_demog_reltime  VAR_demog_relimp  VAR_demog_relalc  \
0             1.0           0.000000          0.333333               0.0   
1             0.0           0.500000          0.500000               0.0   
2             0.0           0.362477          0.666667               0.0   
3             0.0           0.250000          0.500000               1.0   
4             0.0           1.000000          0.666667               0.0   

   VAR_demog_reldrug  VAR_demog_insured  
0                0.0           1.000000  
1                0.0           1.000000  
2                0.0           0.948551  
3                1.0           1.000000  
4                0.0           1.000000  

[5 rows x 1606 columns]

In [37]:
dmri_df.head()

SampleID  VAR_dmri_rsi_meanmotion  VAR_dmri_rsi_meantrans  \
0  NDAR_INV003RTV85                 0.048277                0.107842   
1  NDAR_INV007W6H7B                 0.123424                0.260717   
2  NDAR_INV00BD7VDC                 0.034895                0.063572   
3  NDAR_INV00J52GPG                 0.090428                0.177118   
4  NDAR_INV00LJVZK2                 0.109293                0.137916   

   VAR_dmri_rsi_meanrot  VAR_dmri_rsirni_fib_fxrh  VAR_dmri_rsirni_fib_fxlh  \
0              0.026167                  0.642641                  0.454347   
1              0.031295                  0.511736                  0.444995   
2              0.035819                  0.579827                  0.376808   
3              0.039253                  0.748944                  0.531418   
4              0.088621                  0.653461                  0.466556   

   VAR_dmri_rsirni_fib_cgcrh  VAR_dmri_rsirni_fib_cgclh  \
0                   0.661144                   0.680595   
1                   0.694954                   0.687808   
2                   0.688287                   0.684356   
3                   0.784886                   0.786115   
4                   0.761648                   0.762895   

   VAR_dmri_rsirni_fib_cghrh  VAR_dmri_rsirni_fib_cghlh  ...  \
0                   0.436990                   0.352721  ...   
1                   0.280525                   0.282188  ...   
2                   0.455224                   0.390372  ...   
3                   0.529693                   0.504818  ...   
4                   0.549832                   0.509784  ...   

   VAR_dmri_dtitdgwc_cdsn_srparh  VAR_dmri_dtitdgwc_cdsn_srtmrh  \
0                       0.410964                       0.438377   
1                       0.377634                       0.582441   
2                       0.431732                       0.507917   
3                       0.425010                       0.559717   
4                       0.414396                       0.465082   

   VAR_dmri_dtitdgwc_cdsn_umlrh  VAR_dmri_dtitdgwc_cdsn_fpolerh  \
0                      0.374859                        0.356860   
1                      0.511844                        0.415461   
2                      0.514542                        0.326719   
3                      0.511445                        0.311065   
4                      0.377741                        0.386934   

   VAR_dmri_dtitdgwc_cdsn_tmpolerh  VAR_dmri_dtitdgwc_cdsn_trvtmrh  \
0                         0.404507                        0.451341   
1                         0.409610                        0.605667   
2                         0.436945                        0.503892   
3                         0.406944                        0.469055   
4                         0.423535                        0.455456   

   VAR_dmri_dtitdgwc_cdsn_insularh  VAR_dmri_dtitdgwc_cdsn_meanlh  \
0                         0.682917                       0.353899   
1                         0.789992                       0.356226   
2                         0.769825                       0.432405   
3                         0.770191                       0.521345   
4                         0.746032                       0.438976   

   VAR_dmri_dtitdgwc_cdsn_meanrh  VAR_dmri_dtitdgwc_cortdesikan_mean  
0                       0.352311                            0.338514  
1                       0.486993                            0.410027  
2                       0.445442                            0.426384  
3                       0.505427                            0.502238  
4                       0.366553                            0.388366  

[5 rows x 8950 columns]

In [38]:
smri_df.head()

SampleID  VAR_mrisdp_1  VAR_mrisdp_2  VAR_mrisdp_3  VAR_mrisdp_4  \
0  NDAR_INV003RTV85      0.514482      0.492723      0.564719      0.608634   
1  NDAR_INV007W6H7B      0.492378      0.634718      0.542488      0.702760   
2  NDAR_INV00BD7VDC      0.419207      0.609869      0.624955      0.631281   
3  NDAR_INV00J52GPG      0.650152      0.671636      0.613482      0.648974   
4  NDAR_INV00LJVZK2      0.498476      0.678736      0.593044      0.710899   

   VAR_mrisdp_5  VAR_mrisdp_6  VAR_mrisdp_7  VAR_mrisdp_8  VAR_mrisdp_9  ...  \
0      0.379835      0.599212      0.651285      0.785579      0.577581  ...   
1      0.405910      0.676084      0.741581      0.723435      0.733824  ...   
2      0.360713      0.668857      0.858319      0.813093      0.717377  ...   
3      0.417645      0.684625      0.706660      0.781784      0.790089  ...   
4      0.362234      0.689225      0.806934      0.796490      0.747024  ...   

   VAR_smri_t2w_scs_hpusrh  VAR_smri_t2w_scs_amygdalarh  VAR_smri_t2w_scs_aar  \
0                 0.412440                     0.662313              0.566751   
1                 0.343539                     0.409401              0.623247   
2                 0.428050                     0.603084              0.593682   
3                 0.491223                     0.620191              0.637633   
4                 0.466057                     0.663822              0.648205   

   VAR_smri_t2w_scs_vedcrh  VAR_smri_t2w_scs_wmhint  VAR_smri_t2w_scs_ccps  \
0                 0.561689                 0.299799               0.433791   
1                 0.538122                 0.318531               0.533154   
2                 0.569278                 0.333340               0.385955   
3                 0.634614                 0.523851               0.551688   
4                 0.541166                 0.356725               0.413480   

   VAR_smri_t2w_scs_ccmidps  VAR_smri_t2w_scs_ccct  VAR_smri_t2w_scs_ccmidat  \
0                  0.516903               0.637797                  0.554747   
1                  0.579827               0.574021                  0.541826   
2                  0.601975               0.756808                  0.627347   
3                  0.845774               0.913050                  0.660504   
4                  0.545966               0.672326                  0.633287   

   VAR_smri_t2w_scs_ccat  
0               0.473184  
1               0.571276  
2               0.538305  
3               0.600083  
4               0.497941  

[5 rows x 2697 columns]

### QUESTIONNAIRE

In [56]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import ElasticNet
from sklearn.metrics import accuracy_score
train_coef = []
train_intercept = []
for i in range(1,77):
  sample_ids = list(batch_df.loc[batch_df['Train_'+str(i)]==1]['SampleID'])
  que_np = que_df.loc[que_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:]
  que_np=que_np.astype('float64')
  np.isnan(que_np)
  que_np[np.isnan(que_np)]=1.0
  ocd_np = np.concatenate(ocd_df.loc[ocd_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:])
  ocd_np[ocd_np==2]=1
  ocd_np = ocd_np.astype('int')
  model = LogisticRegression(penalty='elasticnet', solver='saga', l1_ratio=0.8, max_iter=5000).fit(que_np,ocd_np)
  train_coef.append(model.coef_)
  train_intercept.append(model.intercept_)
  print("Progress ===> ",i," model completed")
print(train_coef)
print(train_intercept)
train_coef = np.concatenate(train_coef)
train_intercept = np.concatenate(train_intercept)

Progress ===>  1  model completed
Progress ===>  2  model completed
Progress ===>  3  model completed
Progress ===>  4  model completed
Progress ===>  5  model completed
Progress ===>  6  model completed
Progress ===>  7  model completed
Progress ===>  8  model completed
Progress ===>  9  model completed
Progress ===>  10  model completed
Progress ===>  11  model completed
Progress ===>  12  model completed
Progress ===>  13  model completed
Progress ===>  14  model completed
Progress ===>  15  model completed
Progress ===>  16  model completed
Progress ===>  17  model completed
Progress ===>  18  model completed
Progress ===>  19  model completed
Progress ===>  20  model completed
Progress ===>  21  model completed
Progress ===>  22  model completed
Progress ===>  23  model completed
Progress ===>  24  model completed
Progress ===>  25  model completed
Progress ===>  26  model completed
Progress ===>  27  model completed
Progress ===>  28  model completed
Progress ===>  29  model comp

In [57]:
from sklearn.metrics import confusion_matrix
train_model_coef = np.mean(train_coef, axis=0)
train_model_intercept = np.mean(train_intercept)

sample_ids = list(batch_df.loc[batch_df['Valid']==1]['SampleID'])
que_train_np = que_df.loc[que_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:]
que_train_np = que_train_np.astype('float64')
np.isnan(que_train_np)
que_train_np[np.isnan(que_train_np)]=1.0
ocd_train_np = np.concatenate(ocd_df.loc[ocd_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:])
ocd_train_np[ocd_train_np==2]=1
train_y_prob=[]
for i in range(len(que_train_np)):
  train_y_prob.append(1/(1+np.exp(-(np.dot(que_train_np[i],train_model_coef)+train_model_intercept))))
train_y_pred=np.array(train_y_prob)
train_y_pred[train_y_pred>0.5]=1
train_y_pred[train_y_pred<=0.5]=0
train_y_pred = train_y_pred.astype('int64')
ocd_train_np = ocd_train_np.astype('int64')
print(accuracy_score(ocd_train_np,train_y_pred))
print(confusion_matrix(ocd_train_np,train_y_pred))

0.45
[[17 33]
 [22 28]]


In [58]:
from sklearn.metrics import confusion_matrix
TN, FP, FN, TP = confusion_matrix(ocd_train_np,train_y_pred).ravel()

print(confusion_matrix(ocd_train_np, train_y_pred))

[[17 33]
 [22 28]]


In [59]:
from math import sqrt

P = TP + FN
N = FP + TN
PP = TP + FP
PN = FN + TN

print("Population =", P+N)
print("Prevalence =", P/(P+N))

CK = (2*((TP * TN) - (TN * FP)))/(((TP + FP) * (FP + TN)) + ((TP + FN) * (FN+TN)))
ACC = (TP + TN) / (P + N)
PPV = TP / PP    
FOR = FN / PN
FDR = FP / PP
NPV = TN / PN
TPR = TP / P
FPR = FP / N
FNR = FN / P
TNR = TN / N
LRp = TPR / FPR
LRn = FNR / TNR
MK = PPV + NPV - 1
BM = TPR + TNR - 1
PT = (sqrt(TPR+FPR) - FPR) / (TPR - FPR)
DOR = LRp/LRn
BA = (TPR + TNR) / 2
FS = (2*PPV * TPR) / (PPV + TPR)
FM = sqrt(PPV * TPR)
MCC = sqrt(TPR*TNR*PPV*NPV) - sqrt(FPR*FNR*FDR*FOR)
TS = TP / (TP + FN + FP)
       
print(CK)
print(ACC)
print(PPV)
print(FOR)
print(FDR)
print(NPV)
print(TPR)
print(FPR)
print(TNR)
print(FNR)
print(LRp)
print(LRn)
print(MK)
print(BM)
print(PT)
print(DOR)
print(BA)
print(FS)
print(FM)
print(MCC)
print(TS)

Population = 100
Prevalence = 0.5
-0.034
0.45
0.45901639344262296
0.5641025641025641
0.5409836065573771
0.4358974358974359
0.56
0.66
0.34
0.44
0.8484848484848485
1.2941176470588234
-0.10508617065994108
-0.09999999999999987
-4.4453610171872615
0.6556473829201103
0.45000000000000007
0.5045045045045045
0.5070001778381038
-0.10251154601309118
0.3373493975903614


In [60]:
with open('que_coef.npy', 'wb') as f:
    np.save(f, train_coef)
with open('que_intercept.npy', 'wb') as f:
    np.save(f, train_intercept)

### dMRI

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import ElasticNet
from sklearn.metrics import accuracy_score
train_coef = []
train_intercept = []
for i in range(1,77):
  sample_ids = list(batch_df.loc[batch_df['Train_'+str(i)]==1]['SampleID'])
  dmri_np = dmri_df.loc[dmri_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:]
  dmri_np=dmri_np.astype('float64')
  dmri_np[np.isnan(dmri_np)]=1.0
  ocd_np = np.concatenate(ocd_df.loc[ocd_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:])
  ocd_np[ocd_np==2]=1
  ocd_np = ocd_np.astype('int')
  model = LogisticRegression(penalty='elasticnet', solver='saga', l1_ratio=0.8, max_iter=5000).fit(dmri_np,ocd_np)
  train_coef.append(model.coef_)
  train_intercept.append(model.intercept_)
  print("Progress ===> ",i," model completed")
print(train_coef)
print(train_intercept)
train_coef = np.concatenate(train_coef)
train_intercept = np.concatenate(train_intercept)

Progress ===>  1  model completed
Progress ===>  2  model completed
Progress ===>  3  model completed
Progress ===>  4  model completed
Progress ===>  5  model completed
Progress ===>  6  model completed
Progress ===>  7  model completed
Progress ===>  8  model completed
Progress ===>  9  model completed
Progress ===>  10  model completed
Progress ===>  11  model completed
Progress ===>  12  model completed
Progress ===>  13  model completed
Progress ===>  14  model completed
Progress ===>  15  model completed
Progress ===>  16  model completed
Progress ===>  17  model completed
Progress ===>  18  model completed
Progress ===>  19  model completed
Progress ===>  20  model completed
Progress ===>  21  model completed
Progress ===>  22  model completed
Progress ===>  23  model completed
Progress ===>  24  model completed
Progress ===>  25  model completed
Progress ===>  26  model completed
Progress ===>  27  model completed
Progress ===>  28  model completed
Progress ===>  29  model comp

In [42]:
from sklearn.metrics import confusion_matrix
train_model_coef = np.mean(train_coef, axis=0)
train_model_intercept = np.mean(train_intercept)

sample_ids = list(batch_df.loc[batch_df['Valid']==1]['SampleID'])
dmri_train_np = dmri_df.loc[dmri_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:]
dmri_train_np = dmri_train_np.astype('float64')
np.isnan(dmri_train_np)
dmri_train_np[np.isnan(dmri_train_np)]=1.0
ocd_train_np = np.concatenate(ocd_df.loc[ocd_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:])
ocd_train_np[ocd_train_np==2]=1
train_y_prob=[]
for i in range(len(que_train_np)):
  train_y_prob.append(1/(1+np.exp(-(np.dot(dmri_train_np[i],train_model_coef)+train_model_intercept))))
train_y_pred=np.array(train_y_prob)
train_y_pred[train_y_pred>0.5]=1
train_y_pred[train_y_pred<=0.5]=0
train_y_pred = train_y_pred.astype('int64')
ocd_train_np = ocd_train_np.astype('int64')
print(accuracy_score(ocd_train_np,train_y_pred))
print(confusion_matrix(ocd_train_np,train_y_pred))

0.54
[[22 28]
 [18 32]]


In [43]:
from sklearn.metrics import confusion_matrix
TN, FP, FN, TP = confusion_matrix(ocd_train_np,train_y_pred).ravel()

print(confusion_matrix(ocd_train_np, train_y_pred))

[[22 28]
 [18 32]]


In [44]:
from math import sqrt

P = TP + FN
N = FP + TN
PP = TP + FP
PN = FN + TN

print("Population =", P+N)
print("Prevalence =", P/(P+N))

CK = (2*((TP * TN) - (TN * FP)))/(((TP + FP) * (FP + TN)) + ((TP + FN) * (FN+TN)))
ACC = (TP + TN) / (P + N)
PPV = TP / PP    
FOR = FN / PN
FDR = FP / PP
NPV = TN / PN
TPR = TP / P
FPR = FP / N
FNR = FN / P
TNR = TN / N
LRp = TPR / FPR
LRn = FNR / TNR
MK = PPV + NPV - 1
BM = TPR + TNR - 1
PT = (sqrt(TPR+FPR) - FPR) / (TPR - FPR)
DOR = LRp/LRn
BA = (TPR + TNR) / 2
FS = (2*PPV * TPR) / (PPV + TPR)
FM = sqrt(PPV * TPR)
MCC = sqrt(TPR*TNR*PPV*NPV) - sqrt(FPR*FNR*FDR*FOR)
TS = TP / (TP + FN + FP)
       
print(CK)
print(ACC)
print(PPV)
print(FOR)
print(FDR)
print(NPV)
print(TPR)
print(FPR)
print(TNR)
print(FNR)
print(LRp)
print(LRn)
print(MK)
print(BM)
print(PT)
print(DOR)
print(BA)
print(FS)
print(FM)
print(MCC)
print(TS)

Population = 100
Prevalence = 0.5
0.0352
0.54
0.5333333333333333
0.45
0.4666666666666667
0.55
0.64
0.56
0.44
0.36
1.1428571428571428
0.8181818181818181
0.08333333333333348
0.08000000000000007
6.693063937629157
1.3968253968253967
0.54
0.5818181818181818
0.5842373946721772
0.08164965809277264
0.41025641025641024


In [40]:
with open('dMRI_coef.npy', 'wb') as f:
    np.save(f, train_coef)
with open('dMRI_intercept.npy', 'wb') as f:
    np.save(f, train_intercept)

### sMRI

In [46]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import ElasticNet
from sklearn.metrics import accuracy_score
train_coef = []
train_intercept = []
for i in range(1,77):
  sample_ids = list(batch_df.loc[batch_df['Train_'+str(i)]==1]['SampleID'])
  smri_np = smri_df.loc[smri_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:]
  smri_np = smri_np.astype('float64')
  smri_np[np.isnan(smri_np)]=1.0
  ocd_np = np.concatenate(ocd_df.loc[ocd_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:])
  ocd_np[ocd_np==2]=1
  ocd_np = ocd_np.astype('int')
  model = LogisticRegression(penalty='elasticnet', solver='saga', l1_ratio=0.8, max_iter=5000).fit(smri_np,ocd_np)
  train_coef.append(model.coef_)
  train_intercept.append(model.intercept_)
  print("Progress ===> ",i," model completed")
print(train_coef)
print(train_intercept)
train_coef = np.concatenate(train_coef)
train_intercept = np.concatenate(train_intercept)

Progress ===>  1  model completed
Progress ===>  2  model completed
Progress ===>  3  model completed
Progress ===>  4  model completed
Progress ===>  5  model completed
Progress ===>  6  model completed
Progress ===>  7  model completed
Progress ===>  8  model completed
Progress ===>  9  model completed
Progress ===>  10  model completed
Progress ===>  11  model completed
Progress ===>  12  model completed
Progress ===>  13  model completed
Progress ===>  14  model completed
Progress ===>  15  model completed
Progress ===>  16  model completed
Progress ===>  17  model completed
Progress ===>  18  model completed
Progress ===>  19  model completed
Progress ===>  20  model completed
Progress ===>  21  model completed
Progress ===>  22  model completed
Progress ===>  23  model completed
Progress ===>  24  model completed
Progress ===>  25  model completed
Progress ===>  26  model completed
Progress ===>  27  model completed
Progress ===>  28  model completed
Progress ===>  29  model comp

In [47]:
from sklearn.metrics import confusion_matrix
train_model_coef = np.mean(train_coef, axis=0)
train_model_intercept = np.mean(train_intercept)

sample_ids = list(batch_df.loc[batch_df['Valid']==1]['SampleID'])
smri_train_np = smri_df.loc[smri_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:]
smri_train_np = smri_train_np.astype('float64')
np.isnan(smri_train_np)
smri_train_np[np.isnan(smri_train_np)]=1.0
ocd_train_np = np.concatenate(ocd_df.loc[ocd_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:])
ocd_train_np[ocd_train_np==2]=1
train_y_prob=[]
for i in range(len(que_train_np)):
  train_y_prob.append(1/(1+np.exp(-(np.dot(smri_train_np[i],train_model_coef)+train_model_intercept))))
train_y_pred=np.array(train_y_prob)
train_y_pred[train_y_pred>0.5]=1
train_y_pred[train_y_pred<=0.5]=0
train_y_pred = train_y_pred.astype('int64')
ocd_train_np = ocd_train_np.astype('int64')
print(accuracy_score(ocd_train_np,train_y_pred))
print(confusion_matrix(ocd_train_np,train_y_pred))

0.61
[[24 26]
 [13 37]]


In [48]:
from sklearn.metrics import confusion_matrix
TN, FP, FN, TP = confusion_matrix(ocd_train_np,train_y_pred).ravel()

print(confusion_matrix(ocd_train_np, train_y_pred))

[[24 26]
 [13 37]]


In [49]:
from math import sqrt

P = TP + FN
N = FP + TN
PP = TP + FP
PN = FN + TN

print("Population =", P+N)
print("Prevalence =", P/(P+N))

CK = (2*((TP * TN) - (TN * FP)))/(((TP + FP) * (FP + TN)) + ((TP + FN) * (FN+TN)))
ACC = (TP + TN) / (P + N)
PPV = TP / PP    
FOR = FN / PN
FDR = FP / PP
NPV = TN / PN
TPR = TP / P
FPR = FP / N
FNR = FN / P
TNR = TN / N
LRp = TPR / FPR
LRn = FNR / TNR
MK = PPV + NPV - 1
BM = TPR + TNR - 1
PT = (sqrt(TPR+FPR) - FPR) / (TPR - FPR)
DOR = LRp/LRn
BA = (TPR + TNR) / 2
FS = (2*PPV * TPR) / (PPV + TPR)
FM = sqrt(PPV * TPR)
MCC = sqrt(TPR*TNR*PPV*NPV) - sqrt(FPR*FNR*FDR*FOR)
TS = TP / (TP + FN + FP)
       
print(CK)
print(ACC)
print(PPV)
print(FOR)
print(FDR)
print(NPV)
print(TPR)
print(FPR)
print(TNR)
print(FNR)
print(LRp)
print(LRn)
print(MK)
print(BM)
print(PT)
print(DOR)
print(BA)
print(FS)
print(FM)
print(MCC)
print(TS)

Population = 100
Prevalence = 0.5
0.1056
0.61
0.5873015873015873
0.35135135135135137
0.4126984126984127
0.6486486486486487
0.74
0.52
0.48
0.26
1.423076923076923
0.5416666666666667
0.23595023595023612
0.21999999999999997
2.738623709237193
2.627218934911242
0.61
0.6548672566371682
0.6592443967173135
0.22783558086710667
0.4868421052631579


In [50]:
with open('sMRI_coef.npy', 'wb') as f:
    np.save(f, train_coef)
with open('sMRI_intercept.npy', 'wb') as f:
    np.save(f, train_intercept)

### GENETICS

In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import ElasticNet
from sklearn.metrics import accuracy_score
train_coef = []
train_intercept = []
for i in range(1,77):
  sample_ids = list(batch_df.loc[batch_df['Train_'+str(i)]==1]['SampleID'])
  genetic_np = genetic_df.loc[genetic_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:]
  ocd_np = np.concatenate(ocd_df.loc[ocd_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:])
  ocd_np[ocd_np==2]=1
  ocd_np = ocd_np.astype('int')
  model = LogisticRegression(penalty='elasticnet', solver='saga', l1_ratio=0.8, max_iter=5000).fit(genetic_np,ocd_np)
  train_coef.append(model.coef_)
  train_intercept.append(model.intercept_)
  print("Progress ===> ",i," model completed")
print(train_coef)
print(train_intercept)
train_coef = np.concatenate(train_coef)
train_intercept = np.concatenate(train_intercept)

Progress ===>  1  model completed
Progress ===>  2  model completed
Progress ===>  3  model completed
Progress ===>  4  model completed
Progress ===>  5  model completed
Progress ===>  6  model completed
Progress ===>  7  model completed
Progress ===>  8  model completed
Progress ===>  9  model completed
Progress ===>  10  model completed
Progress ===>  11  model completed
Progress ===>  12  model completed
Progress ===>  13  model completed
Progress ===>  14  model completed
Progress ===>  15  model completed
Progress ===>  16  model completed
Progress ===>  17  model completed
Progress ===>  18  model completed
Progress ===>  19  model completed
Progress ===>  20  model completed
Progress ===>  21  model completed
Progress ===>  22  model completed
Progress ===>  23  model completed
Progress ===>  24  model completed
Progress ===>  25  model completed
Progress ===>  26  model completed
Progress ===>  27  model completed
Progress ===>  28  model completed
Progress ===>  29  model comp

In [53]:
from sklearn.metrics import confusion_matrix
train_model_coef = np.mean(train_coef, axis=0)
train_model_intercept = np.mean(train_intercept)

sample_ids = list(batch_df.loc[batch_df['Valid']==1]['SampleID'])
genetic_train_np = genetic_df.loc[genetic_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:]
ocd_train_np = np.concatenate(ocd_df.loc[ocd_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:])
ocd_train_np[ocd_train_np==2]=1
train_y_prob=[]
for i in range(len(genetic_train_np)):
  train_y_prob.append(1/(1+np.exp(-(np.dot(genetic_train_np[i],train_model_coef)+train_model_intercept))))
train_y_pred=np.array(train_y_prob)
train_y_pred[train_y_pred>0.5]=1
train_y_pred[train_y_pred<=0.5]=0
train_y_pred = train_y_pred.astype('int64')
ocd_train_np = ocd_train_np.astype('int64')
print(accuracy_score(ocd_train_np,train_y_pred))
print(confusion_matrix(ocd_train_np,train_y_pred))

0.61
[[19 31]
 [ 8 42]]


In [54]:
from sklearn.metrics import confusion_matrix
TN, FP, FN, TP = confusion_matrix(ocd_train_np,train_y_pred).ravel()

print(confusion_matrix(ocd_train_np, train_y_pred))

[[19 31]
 [ 8 42]]


In [55]:
from math import sqrt

P = TP + FN
N = FP + TN
PP = TP + FP
PN = FN + TN

print("Population =", P+N)
print("Prevalence =", P/(P+N))

CK = (2*((TP * TN) - (TN * FP)))/(((TP + FP) * (FP + TN)) + ((TP + FN) * (FN+TN)))
ACC = (TP + TN) / (P + N)
PPV = TP / PP    
FOR = FN / PN
FDR = FP / PP
NPV = TN / PN
TPR = TP / P
FPR = FP / N
FNR = FN / P
TNR = TN / N
LRp = TPR / FPR
LRn = FNR / TNR
MK = PPV + NPV - 1
BM = TPR + TNR - 1
PT = (sqrt(TPR+FPR) - FPR) / (TPR - FPR)
DOR = LRp/LRn
BA = (TPR + TNR) / 2
FS = (2*PPV * TPR) / (PPV + TPR)
FM = sqrt(PPV * TPR)
MCC = sqrt(TPR*TNR*PPV*NPV) - sqrt(FPR*FNR*FDR*FOR)
TS = TP / (TP + FN + FP)
       
print(CK)
print(ACC)
print(PPV)
print(FOR)
print(FDR)
print(NPV)
print(TPR)
print(FPR)
print(TNR)
print(FNR)
print(LRp)
print(LRn)
print(MK)
print(BM)
print(PT)
print(DOR)
print(BA)
print(FS)
print(FM)
print(MCC)
print(TS)

Population = 100
Prevalence = 0.5
0.0836
0.61
0.5753424657534246
0.2962962962962963
0.4246575342465753
0.7037037037037037
0.84
0.62
0.38
0.16
1.3548387096774193
0.42105263157894735
0.27904616945712846
0.21999999999999997
2.6741118061793516
3.217741935483871
0.61
0.6829268292682927
0.695188946425989
0.2477703720798115
0.5185185185185185


In [52]:
with open('gen_coef.npy', 'wb') as f:
    np.save(f, train_coef)
with open('gen_intercept.npy', 'wb') as f:
    np.save(f, train_intercept)

### COMBINE

In [64]:
# Weights
acc_gen = 0.61
acc_smri = 0.61
acc_dmri = 0.54
acc_que = 0.45
acc_tot = acc_gen + acc_smri + acc_dmri + acc_que

w_gen = acc_gen / acc_tot
w_smri = acc_smri / acc_tot
w_dmri = acc_dmri / acc_tot
w_que = acc_que / acc_tot

print(w_gen, w_smri, w_dmri, w_que)

0.27601809954751133 0.27601809954751133 0.24434389140271495 0.20361990950226244


In [71]:
# Import coefficients
gen_coef = None
gen_intercept = None
que_coef = None
que_intercept = None
smri_coef = None
smri_intercept = None
dmri_coef = None
dmri_intercept = None

with open('gen_coef.npy', 'rb') as f:
    gen_coef = np.load(f)
with open('gen_intercept.npy', 'rb') as f:
    gen_intercept = np.load(f)
    
with open('que_coef.npy', 'rb') as f:
    que_coef = np.load(f)
with open('que_intercept.npy', 'rb') as f:
    que_intercept = np.load(f)

with open('smri_coef.npy', 'rb') as f:
    smri_coef = np.load(f)
with open('smri_intercept.npy', 'rb') as f:
    smri_intercept = np.load(f)
    
with open('dmri_coef.npy', 'rb') as f:
    dmri_coef = np.load(f)
with open('dmri_intercept.npy', 'rb') as f:
    dmri_intercept = np.load(f)

In [86]:
from sklearn.metrics import confusion_matrix

# gen
train_model_coef = np.mean(gen_coef, axis=0)
train_model_intercept = np.mean(gen_intercept)

sample_ids = list(batch_df.loc[batch_df['Test']==1]['SampleID'])
genetic_train_np = genetic_df.loc[genetic_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:]
ocd_train_np = np.concatenate(ocd_df.loc[ocd_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:])
ocd_train_np[ocd_train_np==2]=1
train_y_prob=[]
for i in range(len(genetic_train_np)):
  train_y_prob.append(1/(1+np.exp(-(np.dot(genetic_train_np[i],train_model_coef)+train_model_intercept))))
gen_y_prob=np.array(train_y_prob)

# sMRI
train_model_coef = np.mean(smri_coef, axis=0)
train_model_intercept = np.mean(smri_intercept)

sample_ids = list(batch_df.loc[batch_df['Test']==1]['SampleID'])
smri_train_np = smri_df.loc[smri_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:]
smri_train_np = smri_train_np.astype('float64')
np.isnan(smri_train_np)
smri_train_np[np.isnan(smri_train_np)]=1.0
ocd_train_np = np.concatenate(ocd_df.loc[ocd_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:])
ocd_train_np[ocd_train_np==2]=1
train_y_prob=[]
for i in range(len(que_train_np)):
  train_y_prob.append(1/(1+np.exp(-(np.dot(smri_train_np[i],train_model_coef)+train_model_intercept))))
smri_y_prob=np.array(train_y_prob)

# dMRI
train_model_coef = np.mean(dmri_coef, axis=0)
train_model_intercept = np.mean(dmri_intercept)

sample_ids = list(batch_df.loc[batch_df['Test']==1]['SampleID'])
dmri_train_np = dmri_df.loc[dmri_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:]
dmri_train_np = dmri_train_np.astype('float64')
np.isnan(dmri_train_np)
dmri_train_np[np.isnan(dmri_train_np)]=1.0
ocd_train_np = np.concatenate(ocd_df.loc[ocd_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:])
ocd_train_np[ocd_train_np==2]=1
train_y_prob=[]
for i in range(len(que_train_np)):
  train_y_prob.append(1/(1+np.exp(-(np.dot(dmri_train_np[i],train_model_coef)+train_model_intercept))))
dmri_y_prob=np.array(train_y_prob)

# que
train_model_coef = np.mean(que_coef, axis=0)
train_model_intercept = np.mean(que_intercept)

sample_ids = list(batch_df.loc[batch_df['Test']==1]['SampleID'])
que_train_np = que_df.loc[que_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:]
que_train_np = que_train_np.astype('float64')
np.isnan(que_train_np)
que_train_np[np.isnan(que_train_np)]=1.0
ocd_train_np = np.concatenate(ocd_df.loc[ocd_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:])
ocd_train_np[ocd_train_np==2]=1
train_y_prob=[]
for i in range(len(que_train_np)):
  train_y_prob.append(1/(1+np.exp(-(np.dot(que_train_np[i],train_model_coef)+train_model_intercept))))
que_y_prob=np.array(train_y_prob)

In [87]:
# Scale Probabilities
wgen_y_prob = gen_y_prob * w_gen
wsmri_y_prob = smri_y_prob * w_smri
wdmri_y_prob = dmri_y_prob * w_dmri
wque_y_prob = que_y_prob * w_que

total_y_prob = wgen_y_prob + wsmri_y_prob + wdmri_y_prob + wque_y_prob

print(total_y_prob)

total_y_prob[total_y_prob>0.5]=1
total_y_prob[total_y_prob<=0.5]=0
total_y_prob = total_y_prob.astype('int64')
ocd_train_np = ocd_train_np.astype('int64')
print(accuracy_score(ocd_train_np,total_y_prob))
print(confusion_matrix(ocd_train_np,total_y_prob))

[0.53752831 0.55028962 0.45762311 0.49728336 0.52255526 0.47895278
 0.57201714 0.52384401 0.53210538 0.48862592 0.5338193  0.50053343
 0.49041893 0.51344586 0.55108933 0.49393034 0.50738538 0.55342413
 0.48895536 0.58973236 0.52268892 0.55020191 0.49728046 0.46367476
 0.54263084 0.49499979 0.59152073 0.51458003 0.54117297 0.55296916
 0.56931477 0.5215281  0.47317075 0.49875643 0.46665206 0.5152812
 0.43480768 0.46073047 0.53248617 0.50091678 0.54594205 0.52713853
 0.53342168 0.50382279 0.50398688 0.51802505 0.51799511 0.53750774
 0.56658107 0.50606249 0.53906501 0.56971702 0.46671364 0.58718077
 0.5137104  0.44867793 0.54215502 0.52465341 0.48035871 0.51342529
 0.49794633 0.54127753 0.54829057 0.52286254 0.52528195 0.55498356
 0.5930054  0.49472448 0.45202155 0.52591711 0.48266514 0.5503224
 0.55620129 0.56547659 0.55983958 0.56125836 0.52236173 0.54359905
 0.53866553 0.47911535 0.53505901 0.55448703 0.49717815 0.55201596
 0.52641726 0.56647347 0.46867934 0.52636212 0.53159691 0.540559

In [88]:
from sklearn.metrics import confusion_matrix
TN, FP, FN, TP = confusion_matrix(ocd_train_np,total_y_prob).ravel()

print(confusion_matrix(ocd_train_np, total_y_prob))

[[16 34]
 [12 38]]


In [89]:
from math import sqrt

P = TP + FN
N = FP + TN
PP = TP + FP
PN = FN + TN

print("Population =", P+N)
print("Prevalence =", P/(P+N))

CK = (2*((TP * TN) - (TN * FP)))/(((TP + FP) * (FP + TN)) + ((TP + FN) * (FN+TN)))
ACC = (TP + TN) / (P + N)
PPV = TP / PP    
FOR = FN / PN
FDR = FP / PP
NPV = TN / PN
TPR = TP / P
FPR = FP / N
FNR = FN / P
TNR = TN / N
LRp = TPR / FPR
LRn = FNR / TNR
MK = PPV + NPV - 1
BM = TPR + TNR - 1
PT = (sqrt(TPR+FPR) - FPR) / (TPR - FPR)
DOR = LRp/LRn
BA = (TPR + TNR) / 2
FS = (2*PPV * TPR) / (PPV + TPR)
FM = sqrt(PPV * TPR)
MCC = sqrt(TPR*TNR*PPV*NPV) - sqrt(FPR*FNR*FDR*FOR)
TS = TP / (TP + FN + FP)
       
print(CK)
print(ACC)
print(PPV)
print(FOR)
print(FDR)
print(NPV)
print(TPR)
print(FPR)
print(TNR)
print(FNR)
print(LRp)
print(LRn)
print(MK)
print(BM)
print(PT)
print(DOR)
print(BA)
print(FS)
print(FM)
print(MCC)
print(TS)

Population = 100
Prevalence = 0.5
0.0256
0.54
0.5277777777777778
0.42857142857142855
0.4722222222222222
0.5714285714285714
0.76
0.68
0.32
0.24
1.1176470588235294
0.75
0.0992063492063493
0.08000000000000007
6.500000000000002
1.4901960784313726
0.54
0.6229508196721312
0.6333333333333333
0.08908708063747481
0.4523809523809524


### AMBIGUOUS CASES

In [92]:
from sklearn.metrics import confusion_matrix

# gen
train_model_coef = np.mean(gen_coef, axis=0)
train_model_intercept = np.mean(gen_intercept)

sample_ids = list(batch_df.loc[batch_df['Experimental']==1]['SampleID'])
genetic_train_np = genetic_df.loc[genetic_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:]
ocd_train_np = np.concatenate(ocd_df.loc[ocd_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:])
train_y_prob=[]
for i in range(len(genetic_train_np)):
  train_y_prob.append(1/(1+np.exp(-(np.dot(genetic_train_np[i],train_model_coef)+train_model_intercept))))
gen_y_prob=np.array(train_y_prob)

# sMRI
train_model_coef = np.mean(smri_coef, axis=0)
train_model_intercept = np.mean(smri_intercept)

sample_ids = list(batch_df.loc[batch_df['Experimental']==1]['SampleID'])
smri_train_np = smri_df.loc[smri_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:]
smri_train_np = smri_train_np.astype('float64')
np.isnan(smri_train_np)
smri_train_np[np.isnan(smri_train_np)]=1.0
ocd_train_np = np.concatenate(ocd_df.loc[ocd_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:])
train_y_prob=[]
for i in range(len(que_train_np)):
  train_y_prob.append(1/(1+np.exp(-(np.dot(smri_train_np[i],train_model_coef)+train_model_intercept))))
smri_y_prob=np.array(train_y_prob)

# dMRI
train_model_coef = np.mean(dmri_coef, axis=0)
train_model_intercept = np.mean(dmri_intercept)

sample_ids = list(batch_df.loc[batch_df['Experimental']==1]['SampleID'])
dmri_train_np = dmri_df.loc[dmri_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:]
dmri_train_np = dmri_train_np.astype('float64')
np.isnan(dmri_train_np)
dmri_train_np[np.isnan(dmri_train_np)]=1.0
ocd_train_np = np.concatenate(ocd_df.loc[ocd_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:])
train_y_prob=[]
for i in range(len(que_train_np)):
  train_y_prob.append(1/(1+np.exp(-(np.dot(dmri_train_np[i],train_model_coef)+train_model_intercept))))
dmri_y_prob=np.array(train_y_prob)

# que
train_model_coef = np.mean(que_coef, axis=0)
train_model_intercept = np.mean(que_intercept)

sample_ids = list(batch_df.loc[batch_df['Experimental']==1]['SampleID'])
que_train_np = que_df.loc[que_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:]
que_train_np = que_train_np.astype('float64')
np.isnan(que_train_np)
que_train_np[np.isnan(que_train_np)]=1.0
ocd_train_np = np.concatenate(ocd_df.loc[ocd_df['SampleID'].isin(sample_ids)].to_numpy()[:,1:])
train_y_prob=[]
for i in range(len(que_train_np)):
  train_y_prob.append(1/(1+np.exp(-(np.dot(que_train_np[i],train_model_coef)+train_model_intercept))))
que_y_prob=np.array(train_y_prob)

In [96]:
# Scale Probabilities
wgen_y_prob = gen_y_prob * w_gen
wsmri_y_prob = smri_y_prob * w_smri
wdmri_y_prob = dmri_y_prob * w_dmri
wque_y_prob = que_y_prob * w_que

total_y_prob = wgen_y_prob + wsmri_y_prob + wdmri_y_prob + wque_y_prob

print(total_y_prob)

total_y_prob[total_y_prob>0.5]=1
total_y_prob[total_y_prob<=0.5]=0
total_y_prob = total_y_prob.astype('int64')

[0.48365025 0.50646058 0.55773127 ... 0.4935331  0.53054271 0.50967575]


In [107]:
# Combine SampleIDs 

PredAmbig = list(zip(sample_ids, total_y_prob))

df = pd.DataFrame(PredAmbig, columns = ["SampleID", "OCD"])

df.to_csv('PredAmbig.csv', index=False)


In [108]:
TP=1
FN=1
FP=1
TF=1

P = TP + FN
N = FP + TN
PP = TP + FP
PN = FN + TN

print("Population =", P+N)
print("Prevalence =", P/(P+N))

CK = (2*((TP * TN) - (TN * FP)))/(((TP + FP) * (FP + TN)) + ((TP + FN) * (FN+TN)))
ACC = (TP + TN) / (P + N)
PPV = TP / PP    
FOR = FN / PN
FDR = FP / PP
NPV = TN / PN
TPR = TP / P
FPR = FP / N
FNR = FN / P
TNR = TN / N
LRp = TPR / FPR
LRn = FNR / TNR
MK = PPV + NPV - 1
BM = TPR + TNR - 1
PT = (sqrt(TPR+FPR) - FPR) / (TPR - FPR)
DOR = LRp/LRn
BA = (TPR + TNR) / 2
FS = (2*PPV * TPR) / (PPV + TPR)
FM = sqrt(PPV * TPR)
MCC = sqrt(TPR*TNR*PPV*NPV) - sqrt(FPR*FNR*FDR*FOR)
TS = TP / (TP + FN + FP)
       
print(CK)
print(ACC)
print(PPV)
print(FOR)
print(FDR)
print(NPV)
print(TPR)
print(FPR)
print(TNR)
print(FNR)
print(LRp)
print(LRn)
print(MK)
print(BM)
print(PT)
print(DOR)
print(BA)
print(FS)
print(FM)
print(MCC)
print(TS)

Population = 19
Prevalence = 0.10526315789473684
0.0
0.8947368421052632
0.5
0.058823529411764705
0.5
0.9411764705882353
0.5
0.058823529411764705
0.9411764705882353
0.5
8.5
0.53125
0.4411764705882353
0.4411764705882353
1.5611020036185113
16.0
0.7205882352941176
0.5
0.5
0.4411764705882353
0.3333333333333333
